### ISSUE TITLE
存在中国汉字时生成文档会缺少内容

### ISSUE THREAD

**Issue by bingool** [raiju/phpMobi#10]
当我测试生成超过2048个字节的汉字时会出现前面目录部分被吞噬的情况，后来我修改了phpMobi/RecordFactory内的mb_str_split方法后可以生成完整的书本了。
我的修改如下，将mb_strlen替换成strlen。希望有大神有更好的方法解决汉字的问题。

	$split_length = ($split_length <= 0) ? 1 : $split_length;

	// $mb_strlen = mb_strlen($string, 'utf-8');
	$mb_strlen = strlen($string);

	$array = array();

	for($i = 0; $i < $mb_strlen; $i += $split_length){
		// $array[] = mb_substr($string, $i, $split_length);
		$array[] = substr($string, $i, $split_length);
	}

	return $array;

**Comment by raiju** [comment]
Ah, I was afraid this would happen, but I never got a good test case. The problem with mb_substr is that it cuts at character level, not at byte level (2048 chars > 2048 bytes for e.g. mandarin chinese). Can you try replacing `substr` by `mb_strcut`? I think you might have to set split length to, say, 2040, to avoid problems if the edges bring in more bytes.

**Comment by raiju** [comment]
Also, do you have an input that breaks at the split level? That would allow me to test it better.

**Comment by bingool** [comment]
you can use this to test.  then you will not see the Title and litle content on .mobi file.
thank you very much to answer me.


`
for($i = 0; $i < 20; $i++){
	$mobi_content->appendChapterTitle(($i+1)."这是什么鬼呀".($i+1));
	for($j = 0; $j < 20; $j++){
		$mobi_content->appendParagraph("P".($i+1).".".($j+1)." 许子晴娇嗲的戳了戳身边男子的手臂，小声抱怨了一句：“爸，你看你说的，我这不是见了偶像太兴奋了吗，哪有你这样拆自己闺女的台的……” ".($i+1).'-'.($j+1));
	}
	$mobi_content->appendPageBreak();
}`

sorry ,when i insert php code ,the style is not beautiful .

**Comment by bingool** [comment]
when i try to use
 `
$mb_strlen = mb_strlen($string, 'utf-8');
$array[] = mb_strcut($string, $i, $split_length);
` 
can not see all content but this time the lost content is in the last.

when i try to use
`
$mb_strlen = strlen($string);
$array[] = mb_strcut($string, $i, $split_length);
`
can see all content but when i click title '20这是什么鬼呀20',I can see a `>` at top,but other content is all good.

i am a new phper and not good at php.

and my english is not good ,hope you can understand what i say ?

**Comment by raiju** [comment]
Thanks for the test case and for trying it, I'll take a look. I probably won't have time this week, but I'll keep you up-to-date.

**Comment by bingool** [comment]
ok, thank you very much. @raiju

**Comment by raiju** [comment]
This bug is fixed in https://github.com/raiju/phpMobi/commit/0e87b96d63f57792fb950262a19e9fab8b4d2e4c, but the TOC issue remains (opened #11 to track that).
