### ISSUE TITLE
Help me with Vietnamese

### ISSUE THREAD

**Issue by canomi** [raiju/phpMobi#8]
When generate .mobi file with vietnamese content, words display not correct.
Plz help me to fix it.
Many thanks
P/s: Ex: "Chương Dương là tên cầu của Việt Nam"

**Comment by raiju** [comment]
Hey, sorry, didn't see your message there. Are you passing the text encoded as UTF-8? Can you send me a picture of what you're seeing? (The kindle previewer should give similar results as the kindle, and will make making screenshots easier).
